http://api-ext-sched.pbp.vip.bf2.yahoo.com/
http://api.pbp.vip.bf2.yahoo.com/
http://flickr.bf2.yahoo.com/
http://pr-preprod-2.pbp.vip.bf2.yahoo.com/
http://pr-preprod.pbp.vip.bf2.yahoo.com/
http://qaxms1.l7.search.vip.bf2.yahoo.com/
http://tripod.bf2.yahoo.com/
http://vop01.cdn.vip.bf2.yahoo.com/
https://api-ext-sched.pbp.vip.bf2.yahoo.com/
https://api.pbp.vip.bf2.yahoo.com/
https://flickr.bf2.yahoo.com/
https://pr-preprod-2.pbp.vip.bf2.yahoo.com/
https://pr-preprod.pbp.vip.bf2.yahoo.com/
https://qaxms1.l7.search.vip.bf2.yahoo.com/
https://tripod.bf2.yahoo.com/
https://tsdbr-mt-meta.yms.vip.bf2.yahoo.com/
https://tsdbr-mt.yms.vip.bf2.yahoo.com/
https://vop01.cdn.vip.bf2.yahoo.com/
