http://ats1.l7.search.vip.ir2.yahoo.com/
http://ats2.member.vip.ir2.yahoo.com/
http://av-beapa10.adx.vip.ir2.yahoo.com/
http://av-beapa10.adx.vip.ir2.yahoo.com:8081/
http://bcn1.prod.fp.vip.ir2.yahoo.com/
http://beap203.cbs.vip.ir2.yahoo.com/
http://beap3.cbs.vip.ir2.yahoo.com/
http://bid-bucket.pbp.vip.ir2.yahoo.com/
http://bid-emea.pbp.vip.ir2.yahoo.com/
http://cache-eu.flickr.vip.ir2.yahoo.com/
http://cm3transport0.ops.ir2.yahoo.com/
http://cm3transport1.ops.ir2.yahoo.com/
http://cm3transport2.ops.ir2.yahoo.com/
http://cm3transport3.ops.ir2.yahoo.com/
http://cm3transport4.ops.ir2.yahoo.com/
http://cm3transport6.ops.ir2.yahoo.com/
http://cm3transport7.ops.ir2.yahoo.com/
http://cm3transport8.ops.ir2.yahoo.com/
http://cm3transport9.ops.ir2.yahoo.com/
http://csc-beapa10.adx.vip.ir2.yahoo.com/
http://csc-beapa10.adx.vip.ir2.yahoo.com:8081/
http://e1.ycpi.ir2.yahoo.com/
http://e1.ycpi.vip.ir2.yahoo.com/
http://e2.ycpi.ir2.yahoo.com/
http://e2.ycpi.vip.ir2.yahoo.com/
http://e3.ycpi.ir2.yahoo.com/
http://e4.ycpi.ir2.yahoo.com/
http://e5.ycpi.ir2.yahoo.com/
http://e6.ycpi.ir2.yahoo.com/
http://e7.ycpi.ir2.yahoo.com/
http://e8.ycpi.ir2.yahoo.com/
http://ea1.ycpi.ir2.yahoo.com/
http://ea2.ycpi.ir2.yahoo.com/
http://edgecast-test.pbp.vip.ir2.yahoo.com/
http://exp-ats1.l7.search.vip.ir2.yahoo.com/
http://flickr.ir2.yahoo.com/
http://japi1.global.media.vip.ir2.yahoo.com/
http://japi25.global.media.ir2.yahoo.com/
http://japi26.global.media.ir2.yahoo.com/
http://japi27.global.media.ir2.yahoo.com/
http://japi28.global.media.ir2.yahoo.com/
http://japi30.global.media.ir2.yahoo.com/
http://japi34.global.media.ir2.yahoo.com/
http://japi35.global.media.ir2.yahoo.com/
http://japi36.global.media.ir2.yahoo.com/
http://japi37.global.media.ir2.yahoo.com/
http://japi38.global.media.ir2.yahoo.com/
http://japi39.global.media.ir2.yahoo.com/
http://japi40.global.media.ir2.yahoo.com/
http://japi41.global.media.ir2.yahoo.com/
http://japi42.global.media.ir2.yahoo.com/
http://japi43.global.media.ir2.yahoo.com/
http://japi44.global.media.ir2.yahoo.com/
http://japi45.global.media.ir2.yahoo.com/
http://japi47.global.media.ir2.yahoo.com/
http://japi48.global.media.ir2.yahoo.com/
http://japi49.global.media.ir2.yahoo.com/
http://japi50.global.media.ir2.yahoo.com/
http://kubeingress2.canary1.ensemble.vip.ir2.yahoo.com/
http://kubeingress2.prod2.ensemble.vip.ir2.yahoo.com/
http://kubeingress3.canary1.ensemble.vip.ir2.yahoo.com/
http://kubeingress3.prod2.ensemble.vip.ir2.yahoo.com/
http://lop01.cdn.vip.ir2.yahoo.com/
http://lop02.cdn.vip.ir2.yahoo.com/
http://lop03.cdn.vip.ir2.yahoo.com/
http://lop04.cdn.vip.ir2.yahoo.com/
http://lop05.cdn.vip.ir2.yahoo.com/
http://media-router-aol1.canary.media.vip.ir2.yahoo.com/
http://media-router-aol1.prod.media.vip.ir2.yahoo.com/
http://media-router-api1.canary.media.vip.ir2.yahoo.com/
http://media-router-api1.prod.media.vip.ir2.yahoo.com/
http://media-router-apple1.prod.media.vip.ir2.yahoo.com/
http://media-router-awsgateway1.prod.media.vip.ir2.yahoo.com/
http://media-router-brb1.prod.media.vip.ir2.yahoo.com/
http://media-router-brb71.prod.media.vip.ir2.yahoo.com/
http://media-router-flurry1.prod.media.vip.ir2.yahoo.com/
http://media-router-flurry2.prod.media.vip.ir2.yahoo.com/
http://media-router-flurry3.prod.media.vip.ir2.yahoo.com/
http://media-router-flurry4.prod.media.vip.ir2.yahoo.com/
http://media-router-fp1.canary.media.vip.ir2.yahoo.com/
http://media-router-fp1.prod1.media.vip.ir2.yahoo.com/
http://media-router-fp2.prod1.media.vip.ir2.yahoo.com/
http://media-router-omega1.canary.media.vip.ir2.yahoo.com/
http://media-router-omega1.prod.media.vip.ir2.yahoo.com/
http://media-router-rc1.prod.media.vip.ir2.yahoo.com/
http://media-router1.canary.media.vip.ir2.yahoo.com/
http://media-router1.prod.media.vip.ir2.yahoo.com/
http://media-router2.prod.media.vip.ir2.yahoo.com/
http://media-router3.prod.media.vip.ir2.yahoo.com/
http://mpr1.ngd.vip.ir2.yahoo.com/
http://mpr2.ngd.vip.ir2.yahoo.com/
http://mscache.grp.vip.ir2.yahoo.com/
http://o1.ycpi.ir2.yahoo.com/
http://o1.ycpi.vip.ir2.yahoo.com/
http://o10.ycpi.ir2.yahoo.com/
http://o11.ycpi.ir2.yahoo.com/
http://o12.ycpi.ir2.yahoo.com/
http://o13.ycpi.ir2.yahoo.com/
http://o14.ycpi.ir2.yahoo.com/
http://o15.ycpi.ir2.yahoo.com/
http://o16.ycpi.ir2.yahoo.com/
http://o17.ycpi.ir2.yahoo.com/
http://o18.ycpi.ir2.yahoo.com/
http://o19.ycpi.ir2.yahoo.com/
http://o2.ycpi.ir2.yahoo.com/
http://o2.ycpi.vip.ir2.yahoo.com/
http://o20.ycpi.ir2.yahoo.com/
http://o21.ycpi.ir2.yahoo.com/
http://o22.ycpi.ir2.yahoo.com/
http://o23.ycpi.ir2.yahoo.com/
http://o24.ycpi.ir2.yahoo.com/
http://o25.ycpi.ir2.yahoo.com/
http://o26.ycpi.ir2.yahoo.com/
http://o27.ycpi.ir2.yahoo.com/
http://o28.ycpi.ir2.yahoo.com/
http://o29.ycpi.ir2.yahoo.com/
http://o3.ycpi.ir2.yahoo.com/
http://o30.ycpi.ir2.yahoo.com/
http://o4.ycpi.ir2.yahoo.com/
http://o5.ycpi.ir2.yahoo.com/
http://o6.ycpi.ir2.yahoo.com/
http://o7.ycpi.ir2.yahoo.com/
http://o8.ycpi.ir2.yahoo.com/
http://o9.ycpi.ir2.yahoo.com/
http://pr-bh.pbp.vip.ir2.yahoo.com/
http://pr-bucket.pbp.vip.ir2.yahoo.com/
http://pr-jetty.pbp.vip.ir2.yahoo.com/
http://pr-preprod.pbp.vip.ir2.yahoo.com/
http://pr.pbp.vip.ir2.yahoo.com/
http://sb1.uni.ir2.yahoo.com:8081/
http://sb2.uni.ir2.yahoo.com:8081/
http://sb3.uni.ir2.yahoo.com:8081/
http://service801002.vespa.mail.ir2.yahoo.com/
http://service801004.vespa.mail.ir2.yahoo.com/
http://service801005.vespa.mail.ir2.yahoo.com/
http://service801006.vespa.mail.ir2.yahoo.com/
http://service801007.vespa.mail.ir2.yahoo.com/
http://service801008.vespa.mail.ir2.yahoo.com/
http://service801009.vespa.mail.ir2.yahoo.com/
http://service801010.vespa.mail.ir2.yahoo.com/
http://service801011.vespa.mail.ir2.yahoo.com/
http://service801012.vespa.mail.ir2.yahoo.com/
http://service801013.vespa.mail.ir2.yahoo.com/
http://service801014.vespa.mail.ir2.yahoo.com/
http://service801015.vespa.mail.ir2.yahoo.com/
http://service801016.vespa.mail.ir2.yahoo.com/
http://service801017.vespa.mail.ir2.yahoo.com/
http://service801018.vespa.mail.ir2.yahoo.com/
http://service801019.vespa.mail.ir2.yahoo.com/
http://service801020.vespa.mail.ir2.yahoo.com/
http://service801021.vespa.mail.ir2.yahoo.com/
http://service801022.vespa.mail.ir2.yahoo.com/
http://service801023.vespa.mail.ir2.yahoo.com/
http://service801024.vespa.mail.ir2.yahoo.com/
http://service801025.vespa.mail.ir2.yahoo.com/
http://service801026.vespa.mail.ir2.yahoo.com/
http://service801027.vespa.mail.ir2.yahoo.com/
http://service801028.vespa.mail.ir2.yahoo.com/
http://service801030.vespa.mail.ir2.yahoo.com/
http://service801031.vespa.mail.ir2.yahoo.com/
http://service801032.vespa.mail.ir2.yahoo.com/
http://service801033.vespa.mail.ir2.yahoo.com/
http://service801034.vespa.mail.ir2.yahoo.com/
http://service801035.vespa.mail.ir2.yahoo.com/
http://service801036.vespa.mail.ir2.yahoo.com/
http://service801037.vespa.mail.ir2.yahoo.com/
http://service801038.vespa.mail.ir2.yahoo.com/
http://service801039.vespa.mail.ir2.yahoo.com/
http://service801040.vespa.mail.ir2.yahoo.com/
http://service801047.vespa.mail.ir2.yahoo.com/
http://service801067.vespa.mail.ir2.yahoo.com/
http://service801068.vespa.mail.ir2.yahoo.com/
http://service801069.vespa.mail.ir2.yahoo.com/
http://service801070.vespa.mail.ir2.yahoo.com/
http://service801071.vespa.mail.ir2.yahoo.com/
http://service801072.vespa.mail.ir2.yahoo.com/
http://service801073.vespa.mail.ir2.yahoo.com/
http://service801074.vespa.mail.ir2.yahoo.com/
http://service801076.vespa.mail.ir2.yahoo.com/
http://spcms.pbp.vip.ir2.yahoo.com/
http://spdc.pbp.vip.ir2.yahoo.com/
http://t1.ycpi.vip.ir2.yahoo.com/
http://t2.ycpi.vip.ir2.yahoo.com/
http://ug.uni.vip.ir2.yahoo.com:8081/
http://ug1.bkt.uni.ir2.yahoo.com:8081/
http://ug1.uni.ir2.yahoo.com:8081/
http://ug10.uni.ir2.yahoo.com:8081/
http://ug11.uni.ir2.yahoo.com:8081/
http://ug2.uni.ir2.yahoo.com:8081/
http://ug3.bkt.uni.ir2.yahoo.com:8081/
http://ug3.uni.ir2.yahoo.com:8081/
http://ug6.uni.ir2.yahoo.com:8081/
http://ug7.uni.ir2.yahoo.com:8081/
http://ug8.uni.ir2.yahoo.com:8081/
http://ugbkt-gw.uni.vip.ir2.yahoo.com:8081/
http://ugprd-sbweb.uni.vip.ir2.yahoo.com:8081/
http://v3transport.ops.vip.ir2.yahoo.com/
http://vop01.cdn.vip.ir2.yahoo.com/
http://w2.src.vip.ir2.yahoo.com/
http://w2.src2.vip.ir2.yahoo.com/
http://w2.src3.vip.ir2.yahoo.com/
http://w2.src4.vip.ir2.yahoo.com/
http://ws2.progrss.vip.ir2.yahoo.com/
https://ats1.l7.search.vip.ir2.yahoo.com/
https://ats2.member.vip.ir2.yahoo.com/
https://av-beapa10.adx.vip.ir2.yahoo.com/
https://bcn1.prod.fp.vip.ir2.yahoo.com/
https://beap203.cbs.vip.ir2.yahoo.com/
https://beap3.cbs.vip.ir2.yahoo.com/
https://bid-bucket.pbp.vip.ir2.yahoo.com/
https://bid-emea.pbp.vip.ir2.yahoo.com/
https://cache-eu.flickr.vip.ir2.yahoo.com/
https://csc-beapa10.adx.vip.ir2.yahoo.com/
https://e1.ycpi.ir2.yahoo.com/
https://e1.ycpi.vip.ir2.yahoo.com/
https://e2.ycpi.ir2.yahoo.com/
https://e2.ycpi.vip.ir2.yahoo.com/
https://e3.ycpi.ir2.yahoo.com/
https://e4.ycpi.ir2.yahoo.com/
https://e5.ycpi.ir2.yahoo.com/
https://e6.ycpi.ir2.yahoo.com/
https://e7.ycpi.ir2.yahoo.com/
https://e8.ycpi.ir2.yahoo.com/
https://ea1.ycpi.ir2.yahoo.com/
https://ea2.ycpi.ir2.yahoo.com/
https://exp-ats1.l7.search.vip.ir2.yahoo.com/
https://flickr.ir2.yahoo.com/
https://kubeingress2.canary1.ensemble.vip.ir2.yahoo.com/
https://kubeingress2.canary2.ensemble.vip.ir2.yahoo.com/
https://kubeingress2.prod1.ensemble.vip.ir2.yahoo.com/
https://kubeingress2.prod2.ensemble.vip.ir2.yahoo.com/
https://kubeingress3.canary1.ensemble.vip.ir2.yahoo.com/
https://kubeingress3.prod1.ensemble.vip.ir2.yahoo.com/
https://kubeingress3.prod2.ensemble.vip.ir2.yahoo.com/
https://lop01.cdn.vip.ir2.yahoo.com/
https://lop02.cdn.vip.ir2.yahoo.com/
https://lop03.cdn.vip.ir2.yahoo.com/
https://lop04.cdn.vip.ir2.yahoo.com/
https://lop05.cdn.vip.ir2.yahoo.com/
https://media-router-aol1.canary.media.vip.ir2.yahoo.com/
https://media-router-aol1.prod.media.vip.ir2.yahoo.com/
https://media-router-api1.canary.media.vip.ir2.yahoo.com/
https://media-router-api1.prod.media.vip.ir2.yahoo.com/
https://media-router-apple1.prod.media.vip.ir2.yahoo.com/
https://media-router-awsgateway1.prod.media.vip.ir2.yahoo.com/
https://media-router-brb1.prod.media.vip.ir2.yahoo.com/
https://media-router-brb71.prod.media.vip.ir2.yahoo.com/
https://media-router-flurry1.prod.media.vip.ir2.yahoo.com/
https://media-router-flurry2.prod.media.vip.ir2.yahoo.com/
https://media-router-flurry3.prod.media.vip.ir2.yahoo.com/
https://media-router-flurry4.prod.media.vip.ir2.yahoo.com/
https://media-router-fp1.canary.media.vip.ir2.yahoo.com/
https://media-router-fp1.prod1.media.vip.ir2.yahoo.com/
https://media-router-fp2.prod1.media.vip.ir2.yahoo.com/
https://media-router-omega1.canary.media.vip.ir2.yahoo.com/
https://media-router-omega1.prod.media.vip.ir2.yahoo.com/
https://media-router-rc1.prod.media.vip.ir2.yahoo.com/
https://media-router1.canary.media.vip.ir2.yahoo.com/
https://media-router1.prod.media.vip.ir2.yahoo.com/
https://media-router2.prod.media.vip.ir2.yahoo.com/
https://media-router3.prod.media.vip.ir2.yahoo.com/
https://mpr1.ngd.vip.ir2.yahoo.com/
https://mpr2.ngd.vip.ir2.yahoo.com/
https://mscache.grp.vip.ir2.yahoo.com/
https://o1.ycpi.ir2.yahoo.com/
https://o1.ycpi.vip.ir2.yahoo.com/
https://o10.ycpi.ir2.yahoo.com/
https://o11.ycpi.ir2.yahoo.com/
https://o12.ycpi.ir2.yahoo.com/
https://o13.ycpi.ir2.yahoo.com/
https://o14.ycpi.ir2.yahoo.com/
https://o15.ycpi.ir2.yahoo.com/
https://o16.ycpi.ir2.yahoo.com/
https://o17.ycpi.ir2.yahoo.com/
https://o18.ycpi.ir2.yahoo.com/
https://o19.ycpi.ir2.yahoo.com/
https://o2.ycpi.ir2.yahoo.com/
https://o2.ycpi.vip.ir2.yahoo.com/
https://o20.ycpi.ir2.yahoo.com/
https://o21.ycpi.ir2.yahoo.com/
https://o22.ycpi.ir2.yahoo.com/
https://o23.ycpi.ir2.yahoo.com/
https://o24.ycpi.ir2.yahoo.com/
https://o25.ycpi.ir2.yahoo.com/
https://o26.ycpi.ir2.yahoo.com/
https://o27.ycpi.ir2.yahoo.com/
https://o28.ycpi.ir2.yahoo.com/
https://o29.ycpi.ir2.yahoo.com/
https://o3.ycpi.ir2.yahoo.com/
https://o30.ycpi.ir2.yahoo.com/
https://o4.ycpi.ir2.yahoo.com/
https://o5.ycpi.ir2.yahoo.com/
https://o6.ycpi.ir2.yahoo.com/
https://o7.ycpi.ir2.yahoo.com/
https://o8.ycpi.ir2.yahoo.com/
https://o9.ycpi.ir2.yahoo.com/
https://pr-bh.pbp.vip.ir2.yahoo.com/
https://pr-bucket.pbp.vip.ir2.yahoo.com/
https://pr-preprod.pbp.vip.ir2.yahoo.com/
https://pr.pbp.vip.ir2.yahoo.com/
https://profile1.member.vip.ir2.yahoo.com/
https://spcms.pbp.vip.ir2.yahoo.com/
https://spdc.pbp.vip.ir2.yahoo.com/
https://sync700099-1.mail.ir2.yahoo.com/
https://sync700099-3.mail.ir2.yahoo.com/
https://sync700099.mail.ir2.yahoo.com/
https://t1.ycpi.vip.ir2.yahoo.com/
https://t2.ycpi.vip.ir2.yahoo.com/
https://uc-vcs-e1-em.corp.ir2.yahoo.com:8443/
https://uc-vcs-e2-em.corp.ir2.yahoo.com:8443/
https://uc-vcs-e3-em.corp.ir2.yahoo.com:8443/
https://uc-vcs-e4-em.corp.ir2.yahoo.com:8443/
https://vop01.cdn.vip.ir2.yahoo.com/
https://vpn-1-gci.corp.ir2.yahoo.com/
https://vpn1-1-gci.corp.ir2.yahoo.com/
https://vpn2-1-gci.corp.ir2.yahoo.com/
https://w2.src2.vip.ir2.yahoo.com/
https://w2.src3.vip.ir2.yahoo.com/
https://w2.src4.vip.ir2.yahoo.com/
https://ws2.progrss.vip.ir2.yahoo.com/
https://ybar1.member.vip.ir2.yahoo.com/
