http://analytics.query.yahoo.com/
http://api-onepush.query.yahoo.com/
http://apple-finance.query.yahoo.com/
http://apple-iwork-finance.query.yahoo.com/
http://fantasysports.query.yahoo.com/
http://finance.query.yahoo.com/
http://gamma-yqlmailapps.query.yahoo.com/
http://geo.query.yahoo.com/
http://groot.query.yahoo.com/
http://locdrop.ipv6.query.yahoo.com/
http://locdrop.query.yahoo.com/
http://myyqldb.query.yahoo.com/
http://onepush.query.yahoo.com/
http://sports.query.yahoo.com/
http://us-locdrop.query.yahoo.com/
http://yvap.query.yahoo.com/
https://analytics.query.yahoo.com/
https://api-onepush.query.yahoo.com/
https://apple-finance.query.yahoo.com/
https://apple-iwork-finance.query.yahoo.com/
https://fantasysports.query.yahoo.com/
https://finance.query.yahoo.com/
https://gamma-yqlmailapps.query.yahoo.com/
https://geo.query.yahoo.com/
https://groot.query.yahoo.com/
https://locdrop.ipv6.query.yahoo.com/
https://locdrop.query.yahoo.com/
https://myyqldb.query.yahoo.com/
https://onepush.query.yahoo.com/
https://sports.query.yahoo.com/
https://us-locdrop.query.yahoo.com/
https://yvap.query.yahoo.com/
