http://ats0.hkac.vip.sg3.yahoo.com/
http://ats1.hkac.vip.sg3.yahoo.com/
http://ats1.l7.search.vip.sg3.yahoo.com/
http://ats2.member.vip.sg3.yahoo.com/
http://ats4.hkac.sg3.yahoo.com/
http://ats5.hkac.sg3.yahoo.com/
http://av-beapa10.adx.vip.sg3.yahoo.com/
http://av-beapa10.adx.vip.sg3.yahoo.com:8081/
http://bcn1.prod.fp.vip.sg3.yahoo.com/
http://beap203.cbs.vip.sg3.yahoo.com/
http://beap3.cbs.vip.sg3.yahoo.com/
http://bid-bucket.pbp.vip.sg3.yahoo.com/
http://bid.pbp.vip.sg3.yahoo.com/
http://bidprod.pbp.vip.sg3.yahoo.com/
http://c1.ycs.sg3.yahoo.com/
http://c1.ycs.vip.sg3.yahoo.com/
http://c2.ycs.sg3.yahoo.com/
http://cache-ap.flickr.vip.sg3.yahoo.com/
http://cm3transport0.ops.sg3.yahoo.com/
http://cm3transport1.ops.sg3.yahoo.com/
http://cm3transport2.ops.sg3.yahoo.com/
http://cm3transport3.ops.sg3.yahoo.com/
http://cm3transport4.ops.sg3.yahoo.com/
http://cm3transport5.ops.sg3.yahoo.com/
http://cm3transport6.ops.sg3.yahoo.com/
http://cm3transport7.ops.sg3.yahoo.com/
http://cm3transport8.ops.sg3.yahoo.com/
http://cm3transport9.ops.sg3.yahoo.com/
http://csc-beapa10.adx.vip.sg3.yahoo.com/
http://csc-beapa10.adx.vip.sg3.yahoo.com:8081/
http://ea2.ycpi.sg3.yahoo.com/
http://edge-hk.nevec.vip.sg3.yahoo.com/
http://exp-ats1.l7.search.vip.sg3.yahoo.com/
http://flickr.sg3.yahoo.com/
http://japi1.global.media.vip.sg3.yahoo.com/
http://kubeingress2.canary1.ensemble.vip.sg3.yahoo.com/
http://kubeingress2.canary2.ensemble.vip.sg3.yahoo.com/
http://kubeingress2.prod1.ensemble.vip.sg3.yahoo.com/
http://kubeingress2.prod2.ensemble.vip.sg3.yahoo.com/
http://kubeingress3.canary1.ensemble.vip.sg3.yahoo.com/
http://kubeingress3.canary2.ensemble.vip.sg3.yahoo.com/
http://kubeingress3.prod1.ensemble.vip.sg3.yahoo.com/
http://kubeingress3.prod2.ensemble.vip.sg3.yahoo.com/
http://lop01.cdn.vip.sg3.yahoo.com/
http://lop02.cdn.vip.sg3.yahoo.com/
http://lop03.cdn.vip.sg3.yahoo.com/
http://lop04.cdn.vip.sg3.yahoo.com/
http://lop05.cdn.vip.sg3.yahoo.com/
http://media-router-abu1.canary.media.vip.sg3.yahoo.com/
http://media-router-abu1.prod.media.vip.sg3.yahoo.com/
http://media-router-api1.canary.media.vip.sg3.yahoo.com/
http://media-router-api1.prod.media.vip.sg3.yahoo.com/
http://media-router-apple1.prod.media.vip.sg3.yahoo.com/
http://media-router-awsgateway1.prod.media.vip.sg3.yahoo.com/
http://media-router-brb1.prod.media.vip.sg3.yahoo.com/
http://media-router-brb71.prod.media.vip.sg3.yahoo.com/
http://media-router-flurry1.prod.media.vip.sg3.yahoo.com/
http://media-router-flurry2.prod.media.vip.sg3.yahoo.com/
http://media-router-flurry3.prod.media.vip.sg3.yahoo.com/
http://media-router-flurry4.prod.media.vip.sg3.yahoo.com/
http://media-router-fp1.canary.media.vip.sg3.yahoo.com/
http://media-router-fp1.prod1.media.vip.sg3.yahoo.com/
http://media-router-fp2.prod1.media.vip.sg3.yahoo.com/
http://media-router-omega1.canary.media.vip.sg3.yahoo.com/
http://media-router-omega1.prod.media.vip.sg3.yahoo.com/
http://media-router-rc1.prod.media.vip.sg3.yahoo.com/
http://media-router1.canary.media.vip.sg3.yahoo.com/
http://media-router1.prod.media.vip.sg3.yahoo.com/
http://media-router2.prod.media.vip.sg3.yahoo.com/
http://media-router3.prod.media.vip.sg3.yahoo.com/
http://mpr1.ngd.vip.sg3.yahoo.com/
http://mpr2.ngd.vip.sg3.yahoo.com/
http://mscache1.grp.vip.sg3.yahoo.com/
http://o1.ycpi.sg3.yahoo.com/
http://o1.ycpi.vip.sg3.yahoo.com/
http://o10.ycpi.sg3.yahoo.com/
http://o11.ycpi.sg3.yahoo.com/
http://o12.ycpi.sg3.yahoo.com/
http://o13.ycpi.sg3.yahoo.com/
http://o14.ycpi.sg3.yahoo.com/
http://o15.ycpi.sg3.yahoo.com/
http://o16.ycpi.sg3.yahoo.com/
http://o17.ycpi.sg3.yahoo.com/
http://o18.ycpi.sg3.yahoo.com/
http://o19.ycpi.sg3.yahoo.com/
http://o2.ycpi.sg3.yahoo.com/
http://o2.ycpi.vip.sg3.yahoo.com/
http://o20.ycpi.sg3.yahoo.com/
http://o21.ycpi.sg3.yahoo.com/
http://o22.ycpi.sg3.yahoo.com/
http://o23.ycpi.sg3.yahoo.com/
http://o3.ycpi.sg3.yahoo.com/
http://o4.ycpi.sg3.yahoo.com/
http://o5.ycpi.sg3.yahoo.com/
http://o6.ycpi.sg3.yahoo.com/
http://o7.ycpi.sg3.yahoo.com/
http://o8.ycpi.sg3.yahoo.com/
http://o9.ycpi.sg3.yahoo.com/
http://pp.edge.nevec.vip.sg3.yahoo.com/
http://pr-ats-2.pbp.vip.sg3.yahoo.com/
http://pr-bh-2.pbp.vip.sg3.yahoo.com/
http://pr-bucket.pbp.vip.sg3.yahoo.com/
http://pr-jetty.pbp.vip.sg3.yahoo.com/
http://pr-preprod-2.pbp.vip.sg3.yahoo.com/
http://pr-preprod.pbp.vip.sg3.yahoo.com/
http://pr.pbp.vip.sg3.yahoo.com/
http://presbucket.pbp.vip.sg3.yahoo.com/
http://private.comet.vip.sg3.yahoo.com/
http://public1.comet.vip.sg3.yahoo.com/
http://r2v4.edge.media.vip.sg3.yahoo.com/
http://redir2.biz.mail.vip.sg3.yahoo.com/
http://spcms.pbp.vip.sg3.yahoo.com/
http://spdc.pbp.vip.sg3.yahoo.com/
http://ugprd-sbweb.yst.vip.sg3.yahoo.com:8081/
http://ugprd-uni.ysm.vip.sg3.yahoo.com:8081/
http://v3transport.ops.vip.sg3.yahoo.com/
http://video-yql.production.omega.sg3.yahoo.com/
http://vop01.cdn.vip.sg3.yahoo.com/
http://w2.src.vip.sg3.yahoo.com/
http://w2.src1.vip.sg3.yahoo.com/
http://w2.src2.vip.sg3.yahoo.com/
http://w2.src3.vip.sg3.yahoo.com/
http://w2.src4.vip.sg3.yahoo.com/
http://ws2.progrss.vip.sg3.yahoo.com/
http://ypa-new.ysm.vip.sg3.yahoo.com:8081/
https://ats0.hkac.vip.sg3.yahoo.com/
https://ats1.hkac.vip.sg3.yahoo.com/
https://ats1.l7.search.vip.sg3.yahoo.com/
https://ats2.member.vip.sg3.yahoo.com/
https://ats4.hkac.sg3.yahoo.com/
https://ats5.hkac.sg3.yahoo.com/
https://av-beapa10.adx.vip.sg3.yahoo.com/
https://bcn1.prod.fp.vip.sg3.yahoo.com/
https://beap203.cbs.vip.sg3.yahoo.com/
https://beap3.cbs.vip.sg3.yahoo.com/
https://bid-bucket.pbp.vip.sg3.yahoo.com/
https://bid.pbp.vip.sg3.yahoo.com/
https://bidprod.pbp.vip.sg3.yahoo.com/
https://c1.ycs.sg3.yahoo.com/
https://c1.ycs.vip.sg3.yahoo.com/
https://c2.ycs.sg3.yahoo.com/
https://cache-ap.flickr.vip.sg3.yahoo.com/
https://csc-beapa10.adx.vip.sg3.yahoo.com/
https://ea2.ycpi.sg3.yahoo.com/
https://edge-hk.nevec.vip.sg3.yahoo.com/
https://exp-ats1.l7.search.vip.sg3.yahoo.com/
https://fe3.cbs.vip.sg3.yahoo.com/
https://flickr.sg3.yahoo.com/
https://kubeingress2.canary1.ensemble.vip.sg3.yahoo.com/
https://kubeingress2.canary2.ensemble.vip.sg3.yahoo.com/
https://kubeingress2.prod1.ensemble.vip.sg3.yahoo.com/
https://kubeingress2.prod2.ensemble.vip.sg3.yahoo.com/
https://kubeingress3.canary1.ensemble.vip.sg3.yahoo.com/
https://kubeingress3.canary2.ensemble.vip.sg3.yahoo.com/
https://kubeingress3.prod1.ensemble.vip.sg3.yahoo.com/
https://kubeingress3.prod2.ensemble.vip.sg3.yahoo.com/
https://lop01.cdn.vip.sg3.yahoo.com/
https://lop02.cdn.vip.sg3.yahoo.com/
https://lop03.cdn.vip.sg3.yahoo.com/
https://lop04.cdn.vip.sg3.yahoo.com/
https://lop05.cdn.vip.sg3.yahoo.com/
https://media-router-abu1.canary.media.vip.sg3.yahoo.com/
https://media-router-abu1.prod.media.vip.sg3.yahoo.com/
https://media-router-api1.canary.media.vip.sg3.yahoo.com/
https://media-router-api1.prod.media.vip.sg3.yahoo.com/
https://media-router-apple1.prod.media.vip.sg3.yahoo.com/
https://media-router-awsgateway1.prod.media.vip.sg3.yahoo.com/
https://media-router-brb1.prod.media.vip.sg3.yahoo.com/
https://media-router-brb71.prod.media.vip.sg3.yahoo.com/
https://media-router-flurry1.prod.media.vip.sg3.yahoo.com/
https://media-router-flurry2.prod.media.vip.sg3.yahoo.com/
https://media-router-flurry3.prod.media.vip.sg3.yahoo.com/
https://media-router-flurry4.prod.media.vip.sg3.yahoo.com/
https://media-router-fp1.canary.media.vip.sg3.yahoo.com/
https://media-router-fp1.prod1.media.vip.sg3.yahoo.com/
https://media-router-fp2.prod1.media.vip.sg3.yahoo.com/
https://media-router-omega1.canary.media.vip.sg3.yahoo.com/
https://media-router-omega1.prod.media.vip.sg3.yahoo.com/
https://media-router-rc1.prod.media.vip.sg3.yahoo.com/
https://media-router1.canary.media.vip.sg3.yahoo.com/
https://media-router1.prod.media.vip.sg3.yahoo.com/
https://media-router2.prod.media.vip.sg3.yahoo.com/
https://media-router3.prod.media.vip.sg3.yahoo.com/
https://mpr1.ngd.vip.sg3.yahoo.com/
https://mpr2.ngd.vip.sg3.yahoo.com/
https://mscache1.grp.vip.sg3.yahoo.com/
https://o1.ycpi.sg3.yahoo.com/
https://o1.ycpi.vip.sg3.yahoo.com/
https://o10.ycpi.sg3.yahoo.com/
https://o11.ycpi.sg3.yahoo.com/
https://o12.ycpi.sg3.yahoo.com/
https://o13.ycpi.sg3.yahoo.com/
https://o14.ycpi.sg3.yahoo.com/
https://o15.ycpi.sg3.yahoo.com/
https://o16.ycpi.sg3.yahoo.com/
https://o17.ycpi.sg3.yahoo.com/
https://o18.ycpi.sg3.yahoo.com/
https://o19.ycpi.sg3.yahoo.com/
https://o2.ycpi.sg3.yahoo.com/
https://o2.ycpi.vip.sg3.yahoo.com/
https://o20.ycpi.sg3.yahoo.com/
https://o21.ycpi.sg3.yahoo.com/
https://o22.ycpi.sg3.yahoo.com/
https://o23.ycpi.sg3.yahoo.com/
https://o3.ycpi.sg3.yahoo.com/
https://o4.ycpi.sg3.yahoo.com/
https://o5.ycpi.sg3.yahoo.com/
https://o6.ycpi.sg3.yahoo.com/
https://o7.ycpi.sg3.yahoo.com/
https://o8.ycpi.sg3.yahoo.com/
https://o9.ycpi.sg3.yahoo.com/
https://pp.edge.nevec.vip.sg3.yahoo.com/
https://pr-ats-2.pbp.vip.sg3.yahoo.com/
https://pr-bh-2.pbp.vip.sg3.yahoo.com/
https://pr-bucket.pbp.vip.sg3.yahoo.com/
https://pr-preprod-2.pbp.vip.sg3.yahoo.com/
https://pr-preprod.pbp.vip.sg3.yahoo.com/
https://pr.pbp.vip.sg3.yahoo.com/
https://presbucket.pbp.vip.sg3.yahoo.com/
https://private.comet.vip.sg3.yahoo.com/
https://profile1.member.vip.sg3.yahoo.com/
https://public1.comet.vip.sg3.yahoo.com/
https://r2v4.edge.media.vip.sg3.yahoo.com/
https://redir2.biz.mail.vip.sg3.yahoo.com/
https://spcms.pbp.vip.sg3.yahoo.com/
https://spdc.pbp.vip.sg3.yahoo.com/
https://video-yql.production.omega.sg3.yahoo.com/
https://vop01.cdn.vip.sg3.yahoo.com/
https://vpn-1-gci.corp.sg3.yahoo.com/
https://w2.src1.vip.sg3.yahoo.com/
https://w2.src2.vip.sg3.yahoo.com/
https://w2.src3.vip.sg3.yahoo.com/
https://w2.src4.vip.sg3.yahoo.com/
https://ws2.progrss.vip.sg3.yahoo.com/
https://ybar1.member.vip.sg3.yahoo.com/
