http://ats0.hkac.vip.tp2.yahoo.com/
http://ats1.hkac.vip.tp2.yahoo.com/
http://beap203.cbs.vip.tp2.yahoo.com/
http://beap3.cbs.vip.tp2.yahoo.com/
http://edge-auction.nevec.vip.tp2.yahoo.com/
http://edge-hk.nevec.vip.tp2.yahoo.com/
http://edge-marketplace.nevec.vip.tp2.yahoo.com/
http://edge-search.nevec.vip.tp2.yahoo.com/
http://edge-serviceplus.nevec.vip.tp2.yahoo.com/
http://edge-shopping.nevec.vip.tp2.yahoo.com/
http://edge-windows.nevec.vip.tp2.yahoo.com/
http://media-router-abu1.canary.media.vip.tp2.yahoo.com/
http://media-router-abu1.prod.media.vip.tp2.yahoo.com/
http://media-router-apple1.prod.media.vip.tp2.yahoo.com/
http://media-router-brb1.prod.media.vip.tp2.yahoo.com/
http://media-router-brb71.prod.media.vip.tp2.yahoo.com/
http://media-router-flurry1.prod.media.vip.tp2.yahoo.com/
http://media-router-flurry2.prod.media.vip.tp2.yahoo.com/
http://media-router-flurry3.prod.media.vip.tp2.yahoo.com/
http://media-router-flurry4.prod.media.vip.tp2.yahoo.com/
http://media-router-fp1.canary.media.vip.tp2.yahoo.com/
http://media-router-fp1.prod1.media.vip.tp2.yahoo.com/
http://media-router-fp2.prod1.media.vip.tp2.yahoo.com/
http://media-router-omega1.canary.media.vip.tp2.yahoo.com/
http://media-router-omega1.prod.media.vip.tp2.yahoo.com/
http://media-router1.canary.media.vip.tp2.yahoo.com/
http://media-router1.prod.media.vip.tp2.yahoo.com/
http://media-router2.prod.media.vip.tp2.yahoo.com/
http://media-router3.prod.media.vip.tp2.yahoo.com/
http://pp.edge.nevec.vip.tp2.yahoo.com/
http://r1.tools.media.vip.tp2.yahoo.com/
http://r2.edge.media.vip.tp2.yahoo.com/
http://r2v4.edge.media.vip.tp2.yahoo.com/
http://twbigdeals.v1.production.omega.tp2.yahoo.com/
http://v1.production.omega.tp2.yahoo.com/
https://ats0.hkac.vip.tp2.yahoo.com/
https://ats1.hkac.vip.tp2.yahoo.com/
https://beap203.cbs.vip.tp2.yahoo.com/
https://beap3.cbs.vip.tp2.yahoo.com/
https://edge-ac1.ec.tp2.yahoo.com/
https://edge-auction.nevec.vip.tp2.yahoo.com/
https://edge-hk.nevec.vip.tp2.yahoo.com/
https://edge-mall1.ec.tp2.yahoo.com/
https://edge-marketplace.nevec.vip.tp2.yahoo.com/
https://edge-search.nevec.vip.tp2.yahoo.com/
https://edge-serviceplus.nevec.vip.tp2.yahoo.com/
https://edge-shopping.nevec.vip.tp2.yahoo.com/
https://edge-windows.nevec.vip.tp2.yahoo.com/
https://fe3.cbs.vip.tp2.yahoo.com/
https://media-router-abu1.canary.media.vip.tp2.yahoo.com/
https://media-router-abu1.prod.media.vip.tp2.yahoo.com/
https://media-router-apple1.prod.media.vip.tp2.yahoo.com/
https://media-router-brb1.prod.media.vip.tp2.yahoo.com/
https://media-router-brb71.prod.media.vip.tp2.yahoo.com/
https://media-router-flurry1.prod.media.vip.tp2.yahoo.com/
https://media-router-flurry2.prod.media.vip.tp2.yahoo.com/
https://media-router-flurry3.prod.media.vip.tp2.yahoo.com/
https://media-router-flurry4.prod.media.vip.tp2.yahoo.com/
https://media-router-fp1.canary.media.vip.tp2.yahoo.com/
https://media-router-fp1.prod1.media.vip.tp2.yahoo.com/
https://media-router-fp2.prod1.media.vip.tp2.yahoo.com/
https://media-router-omega1.canary.media.vip.tp2.yahoo.com/
https://media-router-omega1.prod.media.vip.tp2.yahoo.com/
https://media-router1.canary.media.vip.tp2.yahoo.com/
https://media-router1.prod.media.vip.tp2.yahoo.com/
https://media-router2.prod.media.vip.tp2.yahoo.com/
https://media-router3.prod.media.vip.tp2.yahoo.com/
https://pp.edge.nevec.vip.tp2.yahoo.com/
https://r2.edge.media.vip.tp2.yahoo.com/
https://r2.livehouse.media.vip.tp2.yahoo.com/
https://r2v4.edge.media.vip.tp2.yahoo.com/
https://r2v4.livehouse.media.vip.tp2.yahoo.com/
https://sniproxy.nevec.vip.tp2.yahoo.com/
https://twbigdeals.v1.production.omega.tp2.yahoo.com/
https://v1.production.omega.tp2.yahoo.com/
