http://ats2.member.vip.ne1.yahoo.com/
http://av-beapa10.adx.vip.ne1.yahoo.com/
http://av-beapa10.adx.vip.ne1.yahoo.com:8081/
http://bcn1.prod.fp.vip.ne1.yahoo.com/
http://beap-csca10.adx.vip.ne1.yahoo.com/
http://beap-csca10.adx.vip.ne1.yahoo.com:8081/
http://beap-yca10.adx.vip.ne1.yahoo.com:8081/
http://beap203.cbs.vip.ne1.yahoo.com/
http://beap3.cbs.vip.ne1.yahoo.com/
http://c1.ycs.vip.ne1.yahoo.com/
http://dsptrafficapi.pbp.vip.ne1.yahoo.com/
http://extops.rm.vip.ne1.yahoo.com/
http://kubeingress2.alpha1.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.beta1.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.canary1.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.canary2.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.prod1.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.stage1.ensemble.vip.ne1.yahoo.com/
http://kubeingress2.test1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.alpha1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.beta1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.canary1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.canary2.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.prod1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.prod2.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.stage1.ensemble.vip.ne1.yahoo.com/
http://kubeingress3.test1.ensemble.vip.ne1.yahoo.com/
http://lop01.cdn.vip.ne1.yahoo.com/
http://lop02.cdn.vip.ne1.yahoo.com/
http://lop03.cdn.vip.ne1.yahoo.com/
http://lop04.cdn.vip.ne1.yahoo.com/
http://lop05.cdn.vip.ne1.yahoo.com/
http://media-router-api1.canary.media.vip.ne1.yahoo.com/
http://media-router-api1.prod.media.vip.ne1.yahoo.com/
http://media-router-apple1.prod.media.vip.ne1.yahoo.com/
http://media-router-awsgateway1.prod.media.vip.ne1.yahoo.com/
http://media-router-brb1.prod.media.vip.ne1.yahoo.com/
http://media-router-brb71.prod.media.vip.ne1.yahoo.com/
http://media-router-flurry1.prod.media.vip.ne1.yahoo.com/
http://media-router-flurry2.prod.media.vip.ne1.yahoo.com/
http://media-router-flurry3.prod.media.vip.ne1.yahoo.com/
http://media-router-flurry4.prod.media.vip.ne1.yahoo.com/
http://media-router-fp1.canary.media.vip.ne1.yahoo.com/
http://media-router-fp1.prod1.media.vip.ne1.yahoo.com/
http://media-router-fp2.prod1.media.vip.ne1.yahoo.com/
http://media-router-omega1.canary.media.vip.ne1.yahoo.com/
http://media-router-omega1.prod.media.vip.ne1.yahoo.com/
http://media-router-rc1.prod.media.vip.ne1.yahoo.com/
http://media-router1.canary.media.vip.ne1.yahoo.com/
http://media-router1.prod.media.vip.ne1.yahoo.com/
http://media-router2.prod.media.vip.ne1.yahoo.com/
http://media-router3.prod.media.vip.ne1.yahoo.com/
http://mpr1.ngd.vip.ne1.yahoo.com/
http://mpr2.ngd.vip.ne1.yahoo.com/
http://mscache.grp.vip.ne1.yahoo.com/
http://o1.ycpi.vip.ne1.yahoo.com/
http://o2.ycpi.vip.ne1.yahoo.com/
http://pc-pool-ngn.flickr.vip.ne1.yahoo.com/
http://private.comet.vip.ne1.yahoo.com/
http://public1.comet.vip.ne1.yahoo.com/
http://redir2.biz.mail.vip.ne1.yahoo.com/
http://spcms.pbp.vip.ne1.yahoo.com/
http://spdc.pbp.vip.ne1.yahoo.com/
http://stg-api-v3.pbp.vip.ne1.yahoo.com/
http://v3transport.ops.vip.ne1.yahoo.com/
http://vop01.cdn.vip.ne1.yahoo.com/
http://ws2.progrss.vip.ne1.yahoo.com/
https://ats2.member.vip.ne1.yahoo.com/
https://av-beapa10.adx.vip.ne1.yahoo.com/
https://bcn1.prod.fp.vip.ne1.yahoo.com/
https://beap-csca10.adx.vip.ne1.yahoo.com/
https://beap203.cbs.vip.ne1.yahoo.com/
https://beap3.cbs.vip.ne1.yahoo.com/
https://c1.ycs.vip.ne1.yahoo.com/
https://dsptrafficapi.pbp.vip.ne1.yahoo.com/
https://fe3.cbs.vip.ne1.yahoo.com/
https://kubeingress2.alpha1.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.beta1.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.canary1.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.canary2.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.prod1.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.stage1.ensemble.vip.ne1.yahoo.com/
https://kubeingress2.test1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.alpha1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.beta1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.canary1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.canary2.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.prod1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.prod2.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.stage1.ensemble.vip.ne1.yahoo.com/
https://kubeingress3.test1.ensemble.vip.ne1.yahoo.com/
https://lop01.cdn.vip.ne1.yahoo.com/
https://lop02.cdn.vip.ne1.yahoo.com/
https://lop03.cdn.vip.ne1.yahoo.com/
https://lop04.cdn.vip.ne1.yahoo.com/
https://lop05.cdn.vip.ne1.yahoo.com/
https://media-router-api1.canary.media.vip.ne1.yahoo.com/
https://media-router-api1.prod.media.vip.ne1.yahoo.com/
https://media-router-apple1.prod.media.vip.ne1.yahoo.com/
https://media-router-awsgateway1.prod.media.vip.ne1.yahoo.com/
https://media-router-brb1.prod.media.vip.ne1.yahoo.com/
https://media-router-brb71.prod.media.vip.ne1.yahoo.com/
https://media-router-flurry1.prod.media.vip.ne1.yahoo.com/
https://media-router-flurry2.prod.media.vip.ne1.yahoo.com/
https://media-router-flurry3.prod.media.vip.ne1.yahoo.com/
https://media-router-flurry4.prod.media.vip.ne1.yahoo.com/
https://media-router-fp1.canary.media.vip.ne1.yahoo.com/
https://media-router-fp1.prod1.media.vip.ne1.yahoo.com/
https://media-router-fp2.prod1.media.vip.ne1.yahoo.com/
https://media-router-omega1.canary.media.vip.ne1.yahoo.com/
https://media-router-omega1.prod.media.vip.ne1.yahoo.com/
https://media-router-rc1.prod.media.vip.ne1.yahoo.com/
https://media-router1.canary.media.vip.ne1.yahoo.com/
https://media-router1.prod.media.vip.ne1.yahoo.com/
https://media-router2.prod.media.vip.ne1.yahoo.com/
https://media-router3.prod.media.vip.ne1.yahoo.com/
https://mpr1.ngd.vip.ne1.yahoo.com/
https://mpr2.ngd.vip.ne1.yahoo.com/
https://mscache.grp.vip.ne1.yahoo.com/
https://o1.ycpi.vip.ne1.yahoo.com/
https://o2.ycpi.vip.ne1.yahoo.com/
https://pc-pool-ngn.flickr.vip.ne1.yahoo.com/
https://private.comet.vip.ne1.yahoo.com/
https://profile1.member.vip.ne1.yahoo.com/
https://proxy1.att.vip.ne1.yahoo.com/
https://public1.comet.vip.ne1.yahoo.com/
https://redir2.biz.mail.vip.ne1.yahoo.com/
https://rtb-fe1.cbs.vip.ne1.yahoo.com/
https://sastreseller.ysm.vip.ne1.yahoo.com/
https://sofe3.cbs.vip.ne1.yahoo.com/
https://spcms.pbp.vip.ne1.yahoo.com/
https://spdc.pbp.vip.ne1.yahoo.com/
https://stg-api-v3.pbp.vip.ne1.yahoo.com/
https://vop01.cdn.vip.ne1.yahoo.com/
https://ws2.progrss.vip.ne1.yahoo.com/
https://ybar1.member.vip.ne1.yahoo.com/
